root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main cmd/main.go"
  delay = 0
  exclude_dir = ["node_modules", "assets", "tmp", "testdata", "template", "examples"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = ["cmd", "views", "pkg", "db/migrations", "vendor/github.com/oiweiwei/go-msrpc"]
  include_ext = ["go", "html", "sql"]
  include_file = [".env"]
  kill_delay = "0s"
  log = "air.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  time = false
  silent = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
