// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CertificateAuthority struct {
	ID           int64
	Name         string
	Server       string
	CredentialID int64
}

type CertificateContent struct {
	ID                   int64
	Name                 string
	Encoding             string
	Content              []byte
	UpdatedAt            time.Time
	CreatedAt            time.Time
	CertificateRequestID int64
}

type CertificateCryptographicApi struct {
	ID        int64
	Name      sql.NullString
	Shortname sql.NullString
}

type CertificateRequest struct {
	ID                            int64
	DisplayName                   sql.NullString
	SigningAlgorithm              sql.NullString
	KeyLength                     sql.NullInt64
	RequestedOn                   sql.NullTime
	Status                        sql.NullInt64
	StatusMessage                 sql.NullString
	CertificateCryptographicApiID sql.NullInt64
	SigningRequestApiID           sql.NullInt64
	CipherAlgorithmID             sql.NullInt64
	HashAlgorithmID               sql.NullInt64
}

type CertificateRequestsTimeline struct {
	ID                   int64
	CertificateRequestID int64
	Event                int64
	Status               int64
	UpdatedAt            time.Time
	CreatedAt            time.Time
}

type CipherAlgorithm struct {
	ID      int64
	Keysize sql.NullInt64
	Name    sql.NullString
}

type Credential struct {
	ID       int64
	Username string
	Password string
}

type HashAlgorithm struct {
	ID   int64
	Name sql.NullString
}

type SchedulerCompleted struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
	Log        string
}

type SchedulerFailed struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
	Log        string
}

type SchedulerInprogressset struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
}

type SchedulerQueue struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
}

type SchedulerScheduledset struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	PerformAt  time.Time
	Processor  string
	Arguments  []byte
}

type SigningRequestApi struct {
	ID   int64
	Name sql.NullString
}
