// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Certificate struct {
	ID                      int64
	DisplayName             string
	CommonName              string
	Organization            sql.NullString
	SubjectAlternativeNames sql.NullString
	KeyLength               int64
	RequestedOn             time.Time
	Status                  int64
	StatusMessage           sql.NullString
	CipherAlgorithmID       int64
	HashAlgorithmID         int64
}

type CertificateAuthority struct {
	ID           int64
	Name         string
	Server       string
	CredentialID int64
}

type CertificateContent struct {
	ID            int64
	Name          string
	Encoding      string
	Content       []byte
	UpdatedAt     time.Time
	CreatedAt     time.Time
	CertificateID int64
}

type CertificateCryptographicApi struct {
	ID        int64
	Name      sql.NullString
	Shortname sql.NullString
}

type CertificateRequestAuthority struct {
	ID                     int64
	CertificateID          int64
	CertificateAuthorityID int64
	TemplateName           string
}

type CertificateTimeline struct {
	ID            int64
	CertificateID int64
	Event         int64
	Status        int64
	UpdatedAt     time.Time
	CreatedAt     time.Time
}

type CipherAlgorithm struct {
	ID      int64
	Keysize sql.NullInt64
	Name    sql.NullString
}

type Credential struct {
	ID       int64
	Username string
	Password string
}

type HashAlgorithm struct {
	ID   int64
	Name sql.NullString
}

type SchedulerCompleted struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
	Log        string
}

type SchedulerFailed struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
	Log        string
}

type SchedulerInprogressset struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
}

type SchedulerQueue struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
}

type SchedulerScheduledset struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	PerformAt  time.Time
	Processor  string
	Arguments  []byte
}

type SigningRequestApi struct {
	ID   int64
	Name sql.NullString
}
