// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const certificateRequestsAndHashAlgorithm = `-- name: CertificateRequestsAndHashAlgorithm :many
SELECT r.id AS id,
      r.display_name AS display_name,
      r.key_length AS key_length,
      r.requested_on AS requested_on,
      r.status AS status,
      r.status_message AS status_message,
      h.name AS hash_algorithm,
      c.name AS cipher_algorithm,
      s.name AS signing_request_api,
      capi.name as certificate_cryptographic_api
FROM certificate_requests r
INNER JOIN hash_algorithm h ON r.hash_algorithm_id = h.id
INNER JOIN cipher_algorithm c ON r.cipher_algorithm_id = c.id
INNER JOIN signing_request_api s ON r.signing_request_api_id = s.id
INNER JOIN certificate_cryptographic_api capi ON r.certificate_cryptographic_api_id = capi.id
ORDER BY r.id
`

type CertificateRequestsAndHashAlgorithmRow struct {
	ID                          int64
	DisplayName                 sql.NullString
	KeyLength                   sql.NullInt64
	RequestedOn                 sql.NullTime
	Status                      sql.NullInt64
	StatusMessage               sql.NullString
	HashAlgorithm               sql.NullString
	CipherAlgorithm             sql.NullString
	SigningRequestApi           sql.NullString
	CertificateCryptographicApi sql.NullString
}

func (q *Queries) CertificateRequestsAndHashAlgorithm(ctx context.Context) ([]CertificateRequestsAndHashAlgorithmRow, error) {
	rows, err := q.db.QueryContext(ctx, certificateRequestsAndHashAlgorithm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CertificateRequestsAndHashAlgorithmRow
	for rows.Next() {
		var i CertificateRequestsAndHashAlgorithmRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.KeyLength,
			&i.RequestedOn,
			&i.Status,
			&i.StatusMessage,
			&i.HashAlgorithm,
			&i.CipherAlgorithm,
			&i.SigningRequestApi,
			&i.CertificateCryptographicApi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCompletedJob = `-- name: CountCompletedJob :one
SELECT COUNT(*) as count FROM scheduler_completed
`

func (q *Queries) CountCompletedJob(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompletedJob)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailedJob = `-- name: CountFailedJob :one
SELECT COUNT(*) as count FROM scheduler_failed
`

func (q *Queries) CountFailedJob(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedJob)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInProgressSet = `-- name: CountInProgressSet :one
SELECT COUNT(*) as count FROM scheduler_inprogressset
`

func (q *Queries) CountInProgressSet(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInProgressSet)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScheduledSet = `-- name: CountScheduledSet :one
SELECT COUNT(*) as count FROM scheduler_scheduledset
`

func (q *Queries) CountScheduledSet(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScheduledSet)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSchedulerQueueJob = `-- name: CountSchedulerQueueJob :one
SELECT COUNT(*) as count FROM scheduler_queue
`

func (q *Queries) CountSchedulerQueueJob(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSchedulerQueueJob)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCertCryptoApi = `-- name: CreateCertCryptoApi :one
INSERT INTO certificate_cryptographic_api (
  name, shortname
) VALUES (
  ?, ?
)
RETURNING id, name, shortname
`

type CreateCertCryptoApiParams struct {
	Name      sql.NullString
	Shortname sql.NullString
}

func (q *Queries) CreateCertCryptoApi(ctx context.Context, arg CreateCertCryptoApiParams) (CertificateCryptographicApi, error) {
	row := q.db.QueryRowContext(ctx, createCertCryptoApi, arg.Name, arg.Shortname)
	var i CertificateCryptographicApi
	err := row.Scan(&i.ID, &i.Name, &i.Shortname)
	return i, err
}

const createCertificateAuthority = `-- name: CreateCertificateAuthority :one
INSERT INTO certificate_authorities (
  name,
  server,
  credential_id
) VALUES (
  ?, ?, ?
)
RETURNING id
`

type CreateCertificateAuthorityParams struct {
	Name         string
	Server       string
	CredentialID int64
}

func (q *Queries) CreateCertificateAuthority(ctx context.Context, arg CreateCertificateAuthorityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCertificateAuthority, arg.Name, arg.Server, arg.CredentialID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCertificateContentCsr = `-- name: CreateCertificateContentCsr :one
INSERT INTO certificate_contents (
  csr,
  private_key
) VALUES (
  ?, ?
)
RETURNING id
`

type CreateCertificateContentCsrParams struct {
	Csr        []byte
	PrivateKey []byte
}

func (q *Queries) CreateCertificateContentCsr(ctx context.Context, arg CreateCertificateContentCsrParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCertificateContentCsr, arg.Csr, arg.PrivateKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCertificateRequest = `-- name: CreateCertificateRequest :one
INSERT INTO certificate_requests (
      display_name,
      signing_algorithm,
      key_length,
      status,
      status_message,
      requested_on,
      certificate_cryptographic_api_id,
      signing_request_api_id,
      cipher_algorithm_id,
      hash_algorithm_id
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type CreateCertificateRequestParams struct {
	DisplayName                   sql.NullString
	SigningAlgorithm              sql.NullString
	KeyLength                     sql.NullInt64
	Status                        sql.NullInt64
	StatusMessage                 sql.NullString
	RequestedOn                   sql.NullTime
	CertificateCryptographicApiID sql.NullInt64
	SigningRequestApiID           sql.NullInt64
	CipherAlgorithmID             sql.NullInt64
	HashAlgorithmID               sql.NullInt64
}

func (q *Queries) CreateCertificateRequest(ctx context.Context, arg CreateCertificateRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCertificateRequest,
		arg.DisplayName,
		arg.SigningAlgorithm,
		arg.KeyLength,
		arg.Status,
		arg.StatusMessage,
		arg.RequestedOn,
		arg.CertificateCryptographicApiID,
		arg.SigningRequestApiID,
		arg.CipherAlgorithmID,
		arg.HashAlgorithmID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCipherAlgorithm = `-- name: CreateCipherAlgorithm :one
INSERT INTO cipher_algorithm (
  name, keysize
) VALUES (
  ?, ?
)
RETURNING id, name
`

type CreateCipherAlgorithmParams struct {
	Name    sql.NullString
	Keysize sql.NullInt64
}

type CreateCipherAlgorithmRow struct {
	ID   int64
	Name sql.NullString
}

func (q *Queries) CreateCipherAlgorithm(ctx context.Context, arg CreateCipherAlgorithmParams) (CreateCipherAlgorithmRow, error) {
	row := q.db.QueryRowContext(ctx, createCipherAlgorithm, arg.Name, arg.Keysize)
	var i CreateCipherAlgorithmRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createCompletedJob = `-- name: CreateCompletedJob :one
INSERT INTO scheduler_completed (
  id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments,
  log
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type CreateCompletedJobParams struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
	Log        string
}

func (q *Queries) CreateCompletedJob(ctx context.Context, arg CreateCompletedJobParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createCompletedJob,
		arg.ID,
		arg.Retry,
		arg.RetryCount,
		arg.CreatedAt,
		arg.EnqueuedAt,
		arg.Processor,
		arg.Arguments,
		arg.Log,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
  username,
  password
) VALUES (
  ?, ?
)
RETURNING id
`

type CreateCredentialParams struct {
	Username string
	Password string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCredential, arg.Username, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createFailedJob = `-- name: CreateFailedJob :one
INSERT INTO scheduler_failed (
  id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments,
  log
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type CreateFailedJobParams struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
	Log        string
}

func (q *Queries) CreateFailedJob(ctx context.Context, arg CreateFailedJobParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createFailedJob,
		arg.ID,
		arg.Retry,
		arg.RetryCount,
		arg.CreatedAt,
		arg.EnqueuedAt,
		arg.Processor,
		arg.Arguments,
		arg.Log,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createHashAlgorithm = `-- name: CreateHashAlgorithm :one
INSERT INTO hash_algorithm (
  name
) VALUES (
  ?
)
RETURNING id, name
`

func (q *Queries) CreateHashAlgorithm(ctx context.Context, name sql.NullString) (HashAlgorithm, error) {
	row := q.db.QueryRowContext(ctx, createHashAlgorithm, name)
	var i HashAlgorithm
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createInProgressSet = `-- name: CreateInProgressSet :one
INSERT INTO scheduler_inprogressset (
  id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments
) VALUES (
  ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type CreateInProgressSetParams struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
}

func (q *Queries) CreateInProgressSet(ctx context.Context, arg CreateInProgressSetParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createInProgressSet,
		arg.ID,
		arg.Retry,
		arg.RetryCount,
		arg.CreatedAt,
		arg.EnqueuedAt,
		arg.Processor,
		arg.Arguments,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createScheduledSet = `-- name: CreateScheduledSet :one
INSERT INTO scheduler_scheduledset (
  id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  perform_at,
  processor,
  arguments
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type CreateScheduledSetParams struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	PerformAt  time.Time
	Processor  string
	Arguments  []byte
}

func (q *Queries) CreateScheduledSet(ctx context.Context, arg CreateScheduledSetParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createScheduledSet,
		arg.ID,
		arg.Retry,
		arg.RetryCount,
		arg.CreatedAt,
		arg.EnqueuedAt,
		arg.PerformAt,
		arg.Processor,
		arg.Arguments,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSchedulerQueueJob = `-- name: CreateSchedulerQueueJob :one
INSERT INTO scheduler_queue (
  id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments
) VALUES (
  ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type CreateSchedulerQueueJobParams struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
}

func (q *Queries) CreateSchedulerQueueJob(ctx context.Context, arg CreateSchedulerQueueJobParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createSchedulerQueueJob,
		arg.ID,
		arg.Retry,
		arg.RetryCount,
		arg.CreatedAt,
		arg.EnqueuedAt,
		arg.Processor,
		arg.Arguments,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSigningRequestApi = `-- name: CreateSigningRequestApi :one
INSERT INTO signing_request_api (
  name
) VALUES (
  ?
)
RETURNING id, name
`

func (q *Queries) CreateSigningRequestApi(ctx context.Context, name sql.NullString) (SigningRequestApi, error) {
	row := q.db.QueryRowContext(ctx, createSigningRequestApi, name)
	var i SigningRequestApi
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteCertCryptoApi = `-- name: DeleteCertCryptoApi :exec
DELETE FROM certificate_cryptographic_api
WHERE id = ?
`

func (q *Queries) DeleteCertCryptoApi(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCertCryptoApi, id)
	return err
}

const deleteCertificateAuthority = `-- name: DeleteCertificateAuthority :exec
DELETE FROM certificate_authorities
WHERE id = ?
`

func (q *Queries) DeleteCertificateAuthority(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCertificateAuthority, id)
	return err
}

const deleteCertificateRequest = `-- name: DeleteCertificateRequest :exec
DELETE FROM certificate_requests
WHERE id = ?
`

func (q *Queries) DeleteCertificateRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCertificateRequest, id)
	return err
}

const deleteCipherAlgorithm = `-- name: DeleteCipherAlgorithm :exec
DELETE FROM cipher_algorithm
WHERE id = ?
`

func (q *Queries) DeleteCipherAlgorithm(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCipherAlgorithm, id)
	return err
}

const deleteCompletedJob = `-- name: DeleteCompletedJob :exec
DELETE FROM scheduler_completed
WHERE id = ?
`

func (q *Queries) DeleteCompletedJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCompletedJob, id)
	return err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials
WHERE id = ?
`

func (q *Queries) DeleteCredential(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, id)
	return err
}

const deleteFailedJob = `-- name: DeleteFailedJob :exec
DELETE FROM scheduler_failed
WHERE id = ?
`

func (q *Queries) DeleteFailedJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFailedJob, id)
	return err
}

const deleteHashAlgorithm = `-- name: DeleteHashAlgorithm :exec
DELETE FROM hash_algorithm
WHERE id = ?
`

func (q *Queries) DeleteHashAlgorithm(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHashAlgorithm, id)
	return err
}

const deleteInProgressSet = `-- name: DeleteInProgressSet :exec
DELETE FROM scheduler_inprogressset
WHERE id = ?
`

func (q *Queries) DeleteInProgressSet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInProgressSet, id)
	return err
}

const deleteScheduledSet = `-- name: DeleteScheduledSet :exec
DELETE FROM scheduler_scheduledset
WHERE id = ?
`

func (q *Queries) DeleteScheduledSet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteScheduledSet, id)
	return err
}

const deleteSchedulerQueueJob = `-- name: DeleteSchedulerQueueJob :exec
DELETE FROM scheduler_queue
WHERE id = ?
`

func (q *Queries) DeleteSchedulerQueueJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSchedulerQueueJob, id)
	return err
}

const deleteSigningRequestApi = `-- name: DeleteSigningRequestApi :exec
DELETE FROM signing_request_api
WHERE id = ?
`

func (q *Queries) DeleteSigningRequestApi(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSigningRequestApi, id)
	return err
}

const getCertCryptoApi = `-- name: GetCertCryptoApi :one

SELECT id, name, shortname FROM certificate_cryptographic_api
WHERE id = ? LIMIT 1
`

// ------------------------------------------
// certificate_cryptographic_api
// ------------------------------------------
func (q *Queries) GetCertCryptoApi(ctx context.Context, id int64) (CertificateCryptographicApi, error) {
	row := q.db.QueryRowContext(ctx, getCertCryptoApi, id)
	var i CertificateCryptographicApi
	err := row.Scan(&i.ID, &i.Name, &i.Shortname)
	return i, err
}

const getCertificateAuthority = `-- name: GetCertificateAuthority :one

SELECT ca.id AS id,
      ca.name,
      ca.server,
      c.username AS username,
      c.password AS password,
      c.id AS credential_id
FROM certificate_authorities ca
INNER JOIN credentials c ON ca.credential_id = c.id
WHERE ca.id = ? LIMIT 1
`

type GetCertificateAuthorityRow struct {
	ID           int64
	Name         string
	Server       string
	Username     string
	Password     string
	CredentialID int64
}

// ------------------------------------------
// certificate_authorities
// ------------------------------------------
func (q *Queries) GetCertificateAuthority(ctx context.Context, id int64) (GetCertificateAuthorityRow, error) {
	row := q.db.QueryRowContext(ctx, getCertificateAuthority, id)
	var i GetCertificateAuthorityRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Server,
		&i.Username,
		&i.Password,
		&i.CredentialID,
	)
	return i, err
}

const getCertificateContent = `-- name: GetCertificateContent :one

SELECT id, csr, private_key, public_key
FROM certificate_contents
WHERE id = ? LIMIT 1
`

// ------------------------------------------
// certificate_contents
// ------------------------------------------
func (q *Queries) GetCertificateContent(ctx context.Context, id int64) (CertificateContent, error) {
	row := q.db.QueryRowContext(ctx, getCertificateContent, id)
	var i CertificateContent
	err := row.Scan(
		&i.ID,
		&i.Csr,
		&i.PrivateKey,
		&i.PublicKey,
	)
	return i, err
}

const getCertificateRequest = `-- name: GetCertificateRequest :one

SELECT id,
      display_name,
      signing_algorithm,
      key_length,
      status,
      status_message,
      requested_on,
      certificate_cryptographic_api_id,
      signing_request_api_id,
      cipher_algorithm_id,
      hash_algorithm_id
FROM certificate_requests
WHERE id = ? LIMIT 1
`

type GetCertificateRequestRow struct {
	ID                            int64
	DisplayName                   sql.NullString
	SigningAlgorithm              sql.NullString
	KeyLength                     sql.NullInt64
	Status                        sql.NullInt64
	StatusMessage                 sql.NullString
	RequestedOn                   sql.NullTime
	CertificateCryptographicApiID sql.NullInt64
	SigningRequestApiID           sql.NullInt64
	CipherAlgorithmID             sql.NullInt64
	HashAlgorithmID               sql.NullInt64
}

// ------------------------------------------
// certificate_requests
// ------------------------------------------
func (q *Queries) GetCertificateRequest(ctx context.Context, id int64) (GetCertificateRequestRow, error) {
	row := q.db.QueryRowContext(ctx, getCertificateRequest, id)
	var i GetCertificateRequestRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SigningAlgorithm,
		&i.KeyLength,
		&i.Status,
		&i.StatusMessage,
		&i.RequestedOn,
		&i.CertificateCryptographicApiID,
		&i.SigningRequestApiID,
		&i.CipherAlgorithmID,
		&i.HashAlgorithmID,
	)
	return i, err
}

const getCertificateRequestDetailed = `-- name: GetCertificateRequestDetailed :one
SELECT r.id AS id,
      r.display_name AS display_name,
      r.key_length AS key_length,
      r.requested_on AS requested_on,
      r.status AS status,
      r.status_message AS status_message,
      h.name AS hash_algorithm,
      c.name AS cipher_algorithm,
      s.name AS signing_request_api,
      capi.name as certificate_cryptographic_api
FROM certificate_requests r
INNER JOIN hash_algorithm h ON r.hash_algorithm_id = h.id
INNER JOIN cipher_algorithm c ON r.cipher_algorithm_id = c.id
INNER JOIN signing_request_api s ON r.signing_request_api_id = s.id
INNER JOIN certificate_cryptographic_api capi ON r.certificate_cryptographic_api_id = capi.id
WHERE r.id = ? LIMIT 1
`

type GetCertificateRequestDetailedRow struct {
	ID                          int64
	DisplayName                 sql.NullString
	KeyLength                   sql.NullInt64
	RequestedOn                 sql.NullTime
	Status                      sql.NullInt64
	StatusMessage               sql.NullString
	HashAlgorithm               sql.NullString
	CipherAlgorithm             sql.NullString
	SigningRequestApi           sql.NullString
	CertificateCryptographicApi sql.NullString
}

func (q *Queries) GetCertificateRequestDetailed(ctx context.Context, id int64) (GetCertificateRequestDetailedRow, error) {
	row := q.db.QueryRowContext(ctx, getCertificateRequestDetailed, id)
	var i GetCertificateRequestDetailedRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.KeyLength,
		&i.RequestedOn,
		&i.Status,
		&i.StatusMessage,
		&i.HashAlgorithm,
		&i.CipherAlgorithm,
		&i.SigningRequestApi,
		&i.CertificateCryptographicApi,
	)
	return i, err
}

const getCertificateRequestWithContent = `-- name: GetCertificateRequestWithContent :one
SELECT r.id AS id,
      r.display_name AS display_name,
      r.key_length AS key_length,
      r.requested_on AS requested_on,
      r.status AS status,
      r.status_message AS status_message,
      h.name AS hash_algorithm,
      c.name AS cipher_algorithm,
      s.name AS signing_request_api,
      capi.name as certificate_cryptographic_api,
      cc.csr AS csr,
      cc.private_key AS private_key,
      cc.public_key AS public_key
FROM certificate_requests r
INNER JOIN hash_algorithm h ON r.hash_algorithm_id = h.id
INNER JOIN cipher_algorithm c ON r.cipher_algorithm_id = c.id
INNER JOIN signing_request_api s ON r.signing_request_api_id = s.id
INNER JOIN certificate_cryptographic_api capi ON r.certificate_cryptographic_api_id = capi.id
INNER JOIN certificate_contents cc ON r.certificate_contents_id = cc.id
WHERE r.id = ? LIMIT 1
`

type GetCertificateRequestWithContentRow struct {
	ID                          int64
	DisplayName                 sql.NullString
	KeyLength                   sql.NullInt64
	RequestedOn                 sql.NullTime
	Status                      sql.NullInt64
	StatusMessage               sql.NullString
	HashAlgorithm               sql.NullString
	CipherAlgorithm             sql.NullString
	SigningRequestApi           sql.NullString
	CertificateCryptographicApi sql.NullString
	Csr                         []byte
	PrivateKey                  []byte
	PublicKey                   []byte
}

func (q *Queries) GetCertificateRequestWithContent(ctx context.Context, id int64) (GetCertificateRequestWithContentRow, error) {
	row := q.db.QueryRowContext(ctx, getCertificateRequestWithContent, id)
	var i GetCertificateRequestWithContentRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.KeyLength,
		&i.RequestedOn,
		&i.Status,
		&i.StatusMessage,
		&i.HashAlgorithm,
		&i.CipherAlgorithm,
		&i.SigningRequestApi,
		&i.CertificateCryptographicApi,
		&i.Csr,
		&i.PrivateKey,
		&i.PublicKey,
	)
	return i, err
}

const getCipherAlgorithm = `-- name: GetCipherAlgorithm :one

SELECT id, name, keysize FROM cipher_algorithm
WHERE id = ? LIMIT 1
`

type GetCipherAlgorithmRow struct {
	ID      int64
	Name    sql.NullString
	Keysize sql.NullInt64
}

// ------------------------------------------
// cipher_algorithm
// ------------------------------------------
func (q *Queries) GetCipherAlgorithm(ctx context.Context, id int64) (GetCipherAlgorithmRow, error) {
	row := q.db.QueryRowContext(ctx, getCipherAlgorithm, id)
	var i GetCipherAlgorithmRow
	err := row.Scan(&i.ID, &i.Name, &i.Keysize)
	return i, err
}

const getCompletedJob = `-- name: GetCompletedJob :one

SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments
FROM scheduler_completed
WHERE id = ? LIMIT 1
`

type GetCompletedJobRow struct {
	ID         uuid.UUID
	Retry      bool
	RetryCount int64
	CreatedAt  time.Time
	EnqueuedAt time.Time
	Processor  string
	Arguments  []byte
}

// ------------------------------------------
// scheduler_completed
// ------------------------------------------
func (q *Queries) GetCompletedJob(ctx context.Context, id uuid.UUID) (GetCompletedJobRow, error) {
	row := q.db.QueryRowContext(ctx, getCompletedJob, id)
	var i GetCompletedJobRow
	err := row.Scan(
		&i.ID,
		&i.Retry,
		&i.RetryCount,
		&i.CreatedAt,
		&i.EnqueuedAt,
		&i.Processor,
		&i.Arguments,
	)
	return i, err
}

const getCredential = `-- name: GetCredential :one
SELECT id, username, password FROM credentials
WHERE id = ? LIMIT 1
`

// ------------------------------------------
// credentials
// ------------------------------------------
func (q *Queries) GetCredential(ctx context.Context, id int64) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredential, id)
	var i Credential
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const getFailedJob = `-- name: GetFailedJob :one

SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments
FROM scheduler_queue
WHERE id = ? LIMIT 1
`

// ------------------------------------------
// scheduler_failed
// ------------------------------------------
func (q *Queries) GetFailedJob(ctx context.Context, id uuid.UUID) (SchedulerQueue, error) {
	row := q.db.QueryRowContext(ctx, getFailedJob, id)
	var i SchedulerQueue
	err := row.Scan(
		&i.ID,
		&i.Retry,
		&i.RetryCount,
		&i.CreatedAt,
		&i.EnqueuedAt,
		&i.Processor,
		&i.Arguments,
	)
	return i, err
}

const getHashAlgorithm = `-- name: GetHashAlgorithm :one

SELECT id, name FROM hash_algorithm
WHERE id = ? LIMIT 1
`

// ------------------------------------------
// hash_algorithm
// ------------------------------------------
func (q *Queries) GetHashAlgorithm(ctx context.Context, id int64) (HashAlgorithm, error) {
	row := q.db.QueryRowContext(ctx, getHashAlgorithm, id)
	var i HashAlgorithm
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getInProgressSet = `-- name: GetInProgressSet :one

SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments
FROM scheduler_inprogressset
WHERE id = ? LIMIT 1
`

// ------------------------------------------
// scheduler_inprogressset
// ------------------------------------------
func (q *Queries) GetInProgressSet(ctx context.Context, id uuid.UUID) (SchedulerInprogressset, error) {
	row := q.db.QueryRowContext(ctx, getInProgressSet, id)
	var i SchedulerInprogressset
	err := row.Scan(
		&i.ID,
		&i.Retry,
		&i.RetryCount,
		&i.CreatedAt,
		&i.EnqueuedAt,
		&i.Processor,
		&i.Arguments,
	)
	return i, err
}

const getOneSchedulerQueueJob = `-- name: GetOneSchedulerQueueJob :one
SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments
FROM scheduler_queue
ORDER BY id
LIMIT 1
`

func (q *Queries) GetOneSchedulerQueueJob(ctx context.Context) (SchedulerQueue, error) {
	row := q.db.QueryRowContext(ctx, getOneSchedulerQueueJob)
	var i SchedulerQueue
	err := row.Scan(
		&i.ID,
		&i.Retry,
		&i.RetryCount,
		&i.CreatedAt,
		&i.EnqueuedAt,
		&i.Processor,
		&i.Arguments,
	)
	return i, err
}

const getScheduledSet = `-- name: GetScheduledSet :one
SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  perform_at,
  processor,
  arguments
FROM scheduler_scheduledset
WHERE id = ? LIMIT 1
`

// ------------------------------------------
// scheduler_scheduledset
// ------------------------------------------
func (q *Queries) GetScheduledSet(ctx context.Context, id uuid.UUID) (SchedulerScheduledset, error) {
	row := q.db.QueryRowContext(ctx, getScheduledSet, id)
	var i SchedulerScheduledset
	err := row.Scan(
		&i.ID,
		&i.Retry,
		&i.RetryCount,
		&i.CreatedAt,
		&i.EnqueuedAt,
		&i.PerformAt,
		&i.Processor,
		&i.Arguments,
	)
	return i, err
}

const getSchedulerQueueJob = `-- name: GetSchedulerQueueJob :one

SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments
FROM scheduler_queue
WHERE id = ? LIMIT 1
`

// ------------------------------------------
// scheduler_queue
// ------------------------------------------
func (q *Queries) GetSchedulerQueueJob(ctx context.Context, id uuid.UUID) (SchedulerQueue, error) {
	row := q.db.QueryRowContext(ctx, getSchedulerQueueJob, id)
	var i SchedulerQueue
	err := row.Scan(
		&i.ID,
		&i.Retry,
		&i.RetryCount,
		&i.CreatedAt,
		&i.EnqueuedAt,
		&i.Processor,
		&i.Arguments,
	)
	return i, err
}

const getSigningRequestApi = `-- name: GetSigningRequestApi :one

SELECT id, name FROM signing_request_api
WHERE id = ? LIMIT 1
`

// ------------------------------------------
// signing_request_api
// ------------------------------------------
func (q *Queries) GetSigningRequestApi(ctx context.Context, id int64) (SigningRequestApi, error) {
	row := q.db.QueryRowContext(ctx, getSigningRequestApi, id)
	var i SigningRequestApi
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listCertCryptoApi = `-- name: ListCertCryptoApi :many
SELECT id, name, shortname FROM certificate_cryptographic_api
ORDER BY id
`

func (q *Queries) ListCertCryptoApi(ctx context.Context) ([]CertificateCryptographicApi, error) {
	rows, err := q.db.QueryContext(ctx, listCertCryptoApi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CertificateCryptographicApi
	for rows.Next() {
		var i CertificateCryptographicApi
		if err := rows.Scan(&i.ID, &i.Name, &i.Shortname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificateAuthorities = `-- name: ListCertificateAuthorities :many
SELECT ca.id AS id,
      ca.name,
      ca.server,
      c.username AS username,
      c.password AS password,
      c.id AS credential_id
FROM certificate_authorities ca
INNER JOIN credentials c ON ca.credential_id = c.id
`

type ListCertificateAuthoritiesRow struct {
	ID           int64
	Name         string
	Server       string
	Username     string
	Password     string
	CredentialID int64
}

func (q *Queries) ListCertificateAuthorities(ctx context.Context) ([]ListCertificateAuthoritiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCertificateAuthorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCertificateAuthoritiesRow
	for rows.Next() {
		var i ListCertificateAuthoritiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Server,
			&i.Username,
			&i.Password,
			&i.CredentialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificateRequest = `-- name: ListCertificateRequest :many
SELECT id,
      display_name,
      signing_algorithm,
      key_length,
      status,
      status_message,
      requested_on,
      certificate_cryptographic_api_id,
      signing_request_api_id,
      cipher_algorithm_id,
      hash_algorithm_id
FROM certificate_requests
ORDER BY id
`

type ListCertificateRequestRow struct {
	ID                            int64
	DisplayName                   sql.NullString
	SigningAlgorithm              sql.NullString
	KeyLength                     sql.NullInt64
	Status                        sql.NullInt64
	StatusMessage                 sql.NullString
	RequestedOn                   sql.NullTime
	CertificateCryptographicApiID sql.NullInt64
	SigningRequestApiID           sql.NullInt64
	CipherAlgorithmID             sql.NullInt64
	HashAlgorithmID               sql.NullInt64
}

func (q *Queries) ListCertificateRequest(ctx context.Context) ([]ListCertificateRequestRow, error) {
	rows, err := q.db.QueryContext(ctx, listCertificateRequest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCertificateRequestRow
	for rows.Next() {
		var i ListCertificateRequestRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.SigningAlgorithm,
			&i.KeyLength,
			&i.Status,
			&i.StatusMessage,
			&i.RequestedOn,
			&i.CertificateCryptographicApiID,
			&i.SigningRequestApiID,
			&i.CipherAlgorithmID,
			&i.HashAlgorithmID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCipherAlgorithm = `-- name: ListCipherAlgorithm :many
SELECT id, name, keysize FROM cipher_algorithm
ORDER BY id
`

type ListCipherAlgorithmRow struct {
	ID      int64
	Name    sql.NullString
	Keysize sql.NullInt64
}

func (q *Queries) ListCipherAlgorithm(ctx context.Context) ([]ListCipherAlgorithmRow, error) {
	rows, err := q.db.QueryContext(ctx, listCipherAlgorithm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCipherAlgorithmRow
	for rows.Next() {
		var i ListCipherAlgorithmRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Keysize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedJobs = `-- name: ListCompletedJobs :many
SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments,
  log
FROM scheduler_completed
`

func (q *Queries) ListCompletedJobs(ctx context.Context) ([]SchedulerCompleted, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerCompleted
	for rows.Next() {
		var i SchedulerCompleted
		if err := rows.Scan(
			&i.ID,
			&i.Retry,
			&i.RetryCount,
			&i.CreatedAt,
			&i.EnqueuedAt,
			&i.Processor,
			&i.Arguments,
			&i.Log,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, username, password FROM credentials
`

func (q *Queries) ListCredentials(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(&i.ID, &i.Username, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedJobs = `-- name: ListFailedJobs :many
SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments,
  log
FROM scheduler_failed
`

func (q *Queries) ListFailedJobs(ctx context.Context) ([]SchedulerFailed, error) {
	rows, err := q.db.QueryContext(ctx, listFailedJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerFailed
	for rows.Next() {
		var i SchedulerFailed
		if err := rows.Scan(
			&i.ID,
			&i.Retry,
			&i.RetryCount,
			&i.CreatedAt,
			&i.EnqueuedAt,
			&i.Processor,
			&i.Arguments,
			&i.Log,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHashAlgorithm = `-- name: ListHashAlgorithm :many
SELECT id, name FROM hash_algorithm
ORDER BY id
`

func (q *Queries) ListHashAlgorithm(ctx context.Context) ([]HashAlgorithm, error) {
	rows, err := q.db.QueryContext(ctx, listHashAlgorithm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HashAlgorithm
	for rows.Next() {
		var i HashAlgorithm
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInProgressSet = `-- name: ListInProgressSet :many
SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments
FROM scheduler_inprogressset
`

func (q *Queries) ListInProgressSet(ctx context.Context) ([]SchedulerInprogressset, error) {
	rows, err := q.db.QueryContext(ctx, listInProgressSet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerInprogressset
	for rows.Next() {
		var i SchedulerInprogressset
		if err := rows.Scan(
			&i.ID,
			&i.Retry,
			&i.RetryCount,
			&i.CreatedAt,
			&i.EnqueuedAt,
			&i.Processor,
			&i.Arguments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledSet = `-- name: ListScheduledSet :many
SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  perform_at,
  processor,
  arguments
FROM scheduler_scheduledset
`

func (q *Queries) ListScheduledSet(ctx context.Context) ([]SchedulerScheduledset, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledSet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerScheduledset
	for rows.Next() {
		var i SchedulerScheduledset
		if err := rows.Scan(
			&i.ID,
			&i.Retry,
			&i.RetryCount,
			&i.CreatedAt,
			&i.EnqueuedAt,
			&i.PerformAt,
			&i.Processor,
			&i.Arguments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledSetShouldPerform = `-- name: ListScheduledSetShouldPerform :many
SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  perform_at,
  processor,
  arguments
FROM scheduler_scheduledset
WHERE perform_at <= datetime('now')
`

func (q *Queries) ListScheduledSetShouldPerform(ctx context.Context) ([]SchedulerScheduledset, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledSetShouldPerform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerScheduledset
	for rows.Next() {
		var i SchedulerScheduledset
		if err := rows.Scan(
			&i.ID,
			&i.Retry,
			&i.RetryCount,
			&i.CreatedAt,
			&i.EnqueuedAt,
			&i.PerformAt,
			&i.Processor,
			&i.Arguments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulerQueueJobs = `-- name: ListSchedulerQueueJobs :many
SELECT id,
  retry,
  retry_count,
  created_at,
  enqueued_at,
  processor,
  arguments
FROM scheduler_queue
`

func (q *Queries) ListSchedulerQueueJobs(ctx context.Context) ([]SchedulerQueue, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulerQueueJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerQueue
	for rows.Next() {
		var i SchedulerQueue
		if err := rows.Scan(
			&i.ID,
			&i.Retry,
			&i.RetryCount,
			&i.CreatedAt,
			&i.EnqueuedAt,
			&i.Processor,
			&i.Arguments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSigningRequestApi = `-- name: ListSigningRequestApi :many
SELECT id, name FROM signing_request_api
ORDER BY id
`

func (q *Queries) ListSigningRequestApi(ctx context.Context) ([]SigningRequestApi, error) {
	rows, err := q.db.QueryContext(ctx, listSigningRequestApi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningRequestApi
	for rows.Next() {
		var i SigningRequestApi
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertCryptoApi = `-- name: UpdateCertCryptoApi :exec
UPDATE certificate_cryptographic_api
set name = ?,
shortname = ?
WHERE id = ?
RETURNING id, name, shortname
`

type UpdateCertCryptoApiParams struct {
	Name      sql.NullString
	Shortname sql.NullString
	ID        int64
}

func (q *Queries) UpdateCertCryptoApi(ctx context.Context, arg UpdateCertCryptoApiParams) error {
	_, err := q.db.ExecContext(ctx, updateCertCryptoApi, arg.Name, arg.Shortname, arg.ID)
	return err
}

const updateCertificateAuthority = `-- name: UpdateCertificateAuthority :exec
UPDATE certificate_authorities
set name = ?, server = ?
WHERE id = ?
`

type UpdateCertificateAuthorityParams struct {
	Name   string
	Server string
	ID     int64
}

func (q *Queries) UpdateCertificateAuthority(ctx context.Context, arg UpdateCertificateAuthorityParams) error {
	_, err := q.db.ExecContext(ctx, updateCertificateAuthority, arg.Name, arg.Server, arg.ID)
	return err
}

const updateCertificateContentPublicKey = `-- name: UpdateCertificateContentPublicKey :exec
UPDATE certificate_contents
set public_key = ?
WHERE id = ?
`

type UpdateCertificateContentPublicKeyParams struct {
	PublicKey []byte
	ID        int64
}

func (q *Queries) UpdateCertificateContentPublicKey(ctx context.Context, arg UpdateCertificateContentPublicKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateCertificateContentPublicKey, arg.PublicKey, arg.ID)
	return err
}

const updateCertificateRequestContentId = `-- name: UpdateCertificateRequestContentId :exec
UPDATE certificate_requests
set certificate_contents_id = ?
WHERE id = ?
`

type UpdateCertificateRequestContentIdParams struct {
	CertificateContentsID sql.NullInt64
	ID                    int64
}

func (q *Queries) UpdateCertificateRequestContentId(ctx context.Context, arg UpdateCertificateRequestContentIdParams) error {
	_, err := q.db.ExecContext(ctx, updateCertificateRequestContentId, arg.CertificateContentsID, arg.ID)
	return err
}

const updateCertificateRequestStatus = `-- name: UpdateCertificateRequestStatus :exec
UPDATE certificate_requests
set status = ?, status_message = ?
WHERE id = ?
`

type UpdateCertificateRequestStatusParams struct {
	Status        sql.NullInt64
	StatusMessage sql.NullString
	ID            int64
}

func (q *Queries) UpdateCertificateRequestStatus(ctx context.Context, arg UpdateCertificateRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCertificateRequestStatus, arg.Status, arg.StatusMessage, arg.ID)
	return err
}

const updateCipherAlgorithm = `-- name: UpdateCipherAlgorithm :exec
UPDATE cipher_algorithm
set name = ?, keysize = ?
WHERE id = ?
RETURNING id, name, keysize
`

type UpdateCipherAlgorithmParams struct {
	Name    sql.NullString
	Keysize sql.NullInt64
	ID      int64
}

func (q *Queries) UpdateCipherAlgorithm(ctx context.Context, arg UpdateCipherAlgorithmParams) error {
	_, err := q.db.ExecContext(ctx, updateCipherAlgorithm, arg.Name, arg.Keysize, arg.ID)
	return err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE credentials
set username = ?, password = ?
WHERE id = ?
`

type UpdateCredentialParams struct {
	Username string
	Password string
	ID       int64
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateCredential, arg.Username, arg.Password, arg.ID)
	return err
}

const updateHashAlgorithm = `-- name: UpdateHashAlgorithm :exec
UPDATE hash_algorithm
set name = ?
WHERE id = ?
RETURNING id
`

type UpdateHashAlgorithmParams struct {
	Name sql.NullString
	ID   int64
}

func (q *Queries) UpdateHashAlgorithm(ctx context.Context, arg UpdateHashAlgorithmParams) error {
	_, err := q.db.ExecContext(ctx, updateHashAlgorithm, arg.Name, arg.ID)
	return err
}

const updateSigningRequestApi = `-- name: UpdateSigningRequestApi :exec
UPDATE signing_request_api
set name = ?
WHERE id = ?
RETURNING id, name
`

type UpdateSigningRequestApiParams struct {
	Name sql.NullString
	ID   int64
}

func (q *Queries) UpdateSigningRequestApi(ctx context.Context, arg UpdateSigningRequestApiParams) error {
	_, err := q.db.ExecContext(ctx, updateSigningRequestApi, arg.Name, arg.ID)
	return err
}
